services:
  booking-hotels-service:
    image: alekseynyagan607/booking-hotels-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8071
      - SERVER_PORT=8180
      - EUREKA_HOST=eureka-server
      - EUREKA_PORT=8070
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - KEYCLOAK_HOST=keycloak
      - KEYCLOAK_PORT=8080
      - ZIPKIN_HOST=zipkin
      - ZIPKIN_PORT=9411
      - KAFKA_BROKERS=kafka
      - KAFKA_PORT=9092
    depends_on:
      postgres:
        condition: service_started
      kafka:
        condition: service_started
      logstash:
        condition: service_started
      config-server:
        condition: service_healthy
    ports:
      - "8180:8180"

  user-service:
    image: alekseynyagan607/user-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8071
      - EUREKA_HOST=eureka-server
      - EUREKA_PORT=8070
      - SERVER_PORT=8073
      - ZIPKIN_HOST=zipkin
      - ZIPKIN_PORT=9411
      - KEYCLOAK_HOST=keycloak
      - KEYCLOAK_PORT=8080
      - KEYCLOAK_REALM=booking-hotels-realm
      - KEYCLOAK_USERNAME=admin
      - KEYCLOAK_PASSWORD=adminpass
      - KEYCLOAK_RESOURCE=booking-hotels
      - KEYCLOAK_SECRET=4aQS25UnlMEmQbpsIdR1GKzWl60BH4Bs
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_started
      gateway-server:
        condition: service_started
      logstash:
        condition: service_started
    ports:
      - "8073:8073"

  statistic-service:
    image: alekseynyagan607/statistic-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8071
      - EUREKA_HOST=eureka-server
      - EUREKA_PORT=8070
      - SERVER_PORT=8181
      - ZIPKIN_HOST=zipkin
      - ZIPKIN_PORT=9411
      - KEYCLOAK_HOST=keycloak
      - KEYCLOAK_PORT=8080
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_DB_NAME=analytics
      - CLICKHOUSE_USER=analytics_user
      - CLICKHOUSE_PASSWORD=analytics_pass
      - KAFKA_BROKERS=kafka
      - KAFKA_PORT=9092
    depends_on:
      clickhouse:
        condition: service_started
      kafka:
        condition: service_started
      logstash:
        condition: service_started
      config-server:
        condition: service_healthy
    ports:
      - "8181:8181"

  config-server:
    extends:
      service: config-server
      file: services.yaml

  eureka-server:
    image: alekseynyagan607/eureka-server:latest
    ports:
      - "8070:8070"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8071
      - SERVER_PORT=8070
    depends_on:
      config-server:
        condition: service_healthy

  gateway-server:
    image: alekseynyagan607/gateway-server:latest
    ports:
      - "8072:8072"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8071
      - SERVER_PORT=8072
      - KEYCLOAK_HOST=keycloak
      - KEYCLOAK_PORT=8080
      - KEYCLOAK_CLIENT_ID=booking-hotels
      - KEYCLOAK_CLIENT_SECRET=4aQS25UnlMEmQbpsIdR1GKzWl60BH4Bs
      - ZIPKIN_HOST=zipkin
      - ZIPKIN_PORT=9411
      - EUREKA_HOST=eureka-server
      - EUREKA_PORT=8070
    depends_on:
      config-server:
        condition: service_healthy
      logstash:
        condition: service_started
      keycloak:
        condition: service_healthy

  postgres:
    extends:
      service: postgres
      file: services.yaml
    ports:
      - "5432:5432"

  keycloak-postgres:
    extends:
      service: keycloak-postgres
      file: services.yaml
    ports:
      - "5433:5432"

  keycloak:
    extends:
      service: keycloak
      file: services.yaml
    ports:
      - "8080:8080"

  zookeeper:
    extends:
      service: zookeeper
      file: services.yaml
    ports:
      - "2181:2181"

  kafka:
    extends:
      service: kafka
      file: services.yaml
    ports:
      - "9092:9092"

  elasticsearch:
    extends:
      service: elasticsearch
      file: services.yaml
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    extends:
      service: kibana
      file: services.yaml
    ports:
      - "5601:5601"

  logstash:
    extends:
      service: logstash
      file: services.yaml
    ports:
      - "5000:5000"

  zipkin:
    extends:
      service: zipkin
      file: services.yaml
    ports:
      - "9411:9411"

  prometheus:
    extends:
      service: prometheus
      file: services.yaml
    ports:
      - "9090:9090"

  grafana:
    extends:
      service: grafana
      file: services.yaml
    ports:
      - "3000:3000"

  pgadmin:
    image: dpage/pgadmin4:9.0.0
    restart: "no"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
      - ./docker/pgadmin/pgpass:/pgadmin4/pgpass
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80/misc/ping || exit -1
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    depends_on:
      - postgres
    entrypoint: /bin/sh -c "chmod 600 /pgadmin4/pgpass; /entrypoint.sh;"

  clickhouse:
    image: clickhouse/clickhouse-server:25.9.3.48
    container_name: clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_USER=analytics_user
      - CLICKHOUSE_PASSWORD=analytics_pass
      - CLICKHOUSE_DB=analytics
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server

volumes:
  pgadmin_data:
  postgres_data:
  mongodb_data:
  esdata1:
  prometheus_data:
  clickhouse_data:
  clickhouse_logs: