spring:
  application:
    name: config-server
  profiles:
    active:
      - native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

server:
  port: ${SERVER_PORT:8071}

encrypt:
  key: secretkey