spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/booking_hotels
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 50
    show-sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/booking_hotels
    user: postgres
    password: postgres
    analytics-enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:localhost}:8080/realms/booking-hotels-realm
          jwk-set-uri: http://${KEYCLOAK_HOST:localhost}:8080/realms/booking-hotels-realm/protocol/openid-connect/certs
  cloud:
    stream:
      output-bindings: producer
      bindings:
        producer-out-0:
          destination: statistic
      kafka:
        binder:
          enableObservation: true
          transactionIdPrefix: statistic-
          brokers: ${KAFKA_BROKERS:localhost}:9092
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8070/eureka/
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
server:
  port: 8180
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true