server:
  port: ${SERVER_PORT:8072}
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:eureka-server}:${EUREKA_PORT:8070}/eureka/
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/realms/booking-hotels-realm/protocol/openid-connect/auth
            token-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/realms/booking-hotels-realm/protocol/openid-connect/token
            user-info-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/realms/booking-hotels-realm/protocol/openid-connect/userinfo
            issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/realms/booking-hotels-realm
            user-name-attribute: preferred_username
        registration:
          keycloak:
            provider: keycloak
            client-id: ${KEYCLOAK_CLIENT_ID:booking-hotels}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:4aQS25UnlMEmQbpsIdR1GKzWl60BH4Bs}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
              - roles
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}
            - RemoveRequestHeader=Cookie, Set-Cookie
        - id: booking-hotels-service
          uri: lb://booking-hotels-service
          predicates:
            - Path=/booking-hotels/**
          filters:
            - RewritePath=/booking-hotels/(?<path>.*), /$\{path}
            - RemoveRequestHeader=Cookie, Set-Cookie
        - id: statistic-service
          uri: lb://statistic-service
          predicates:
            - Path=/statistic/**
          filters:
            - RewritePath=/statistic/(?<path>.*), /$\{path}
            - RemoveRequestHeader=Cookie, Set-Cookie
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:zipkin}:${ZIPKIN_PORT:9411}/api/v2/spans