server:
  port: 8072
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8070/eureka/
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}
            - RemoveRequestHeader=Cookie, Set-Cookie
        - id: booking-hotels-service
          uri: lb://booking-hotels-service
          predicates:
            - Path=/booking-hotels/**
          filters:
            - RewritePath=/booking-hotels/(?<path>.*), /$\{path}
            - RemoveRequestHeader=Cookie, Set-Cookie
        - id: statistic-service
          uri: lb://statistic-service
          predicates:
            - Path=/statistic/**
          filters:
            - RewritePath=/statistic/(?<path>.*), /$\{path}
            - RemoveRequestHeader=Cookie, Set-Cookie
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans